project:
  type: book
  output-dir: _output

toc: true
number-sections: true

book:
  title: "Community views on diversity, equity, and inclusion in the Astropy project"
  author: 
   - name: Dan Sholler
     email: dan@orgmycology.com
   - name: Beth Duckles
     email: beth@orgmycology.com
   - name: Jonah Duckles
     email: jonah@orgmycology.com
  date: "April 18, 2024"
  downloads: [pdf]
  page-footer:
    left: |
     A report on community views of Diversity Equity and Inclusion (DEI) in the Astropy community
    right: |
      [![](/short_logo.png)](https://orgmycology.com)
  cover-image: cover.png
  favicon: cover.png
  site-url: https://astropy-dei.orgmycology.com
  repo-url: https://github.com/orgmycology/astropy-dei
  repo-branch: main
  repo-actions: [edit, issue]
  sidebar:
    logo: cover.png
    style: docked
    background: light
    collapse-section: 1
    border: true
  chapters:
    - index.md
    - part: Introduction and Methods
      chapters:
        - intro-background.md
        - methods.md
    - part: Findings  
      chapters:
        - findings-overview.md
        - community-recs.md
        - consultant-insights.md
  appendices:
    - interview-protocol.md 
format:
  html:
    number-depth: 1
    theme: flatly
    include-in-header:
      - text: |
          <script defer data-domain="reports.orgmycology.com" src="https://a.duckles.nz/js/script.js"></script>
  pdf:
    cover-image: cover.png
    documentclass: scrbook
    papersize: a4
