on:
  push:
    branches: main
  pull_request:
    branches: main
  # to be able to trigger a manual build
  workflow_dispatch:

name: Render and deploy Book to Cloudflare

jobs:
  build-deploy:
    runs-on: self-hosted 
    #runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      #- name: Install Quarto
      #  uses: quarto-dev/quarto-actions/setup@v2
      #  with:
      #    version: 1.3.450
      #    tinytex: false

      - name: Render book to all formats
        # Add any command line argument needed
        uses: quarto-dev/quarto-actions/render@v2

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: astropy-dei
          directory: './_output'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

